#!/bin/sh

if [ ! -d "$SNAP_USER_DATA/etc" ]; then
  mkdir $SNAP_USER_DATA/etc/
  cp -R $SNAP/etc/protect-daemon.conf $SNAP_USER_DATA/etc/protect-daemon.conf
fi

exec "$SNAP/bin/protect-daemon" "$@"
